# Generated by Django 4.2.16 on 2025-02-20 08:43

from django.db import migrations, models
import nightlife.methods


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Votre nom / pseudo')),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('town', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ville')),
                ('thumbnail', models.ImageField(blank=True, upload_to=nightlife.methods.PathAndRename('users/'))),
                ('short_biography', models.CharField(blank=True, max_length=100, verbose_name='Vous en quelques mots')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('is_active', models.BooleanField(default=True)),
                ('is_promoter', models.BooleanField(default=False, verbose_name='Êtes-vous organisateur ?')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
