# Generated by Django 4.2.16 on 2025-03-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='related_artists',
            field=models.ManyToManyField(blank=True, to='artists.artist'),
        ),
    ]
