# Generated by Django 4.2.16 on 2025-03-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_related_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='related_artists',
        ),
    ]
